server: 
    # 服务端口
    port: 8010
    # 服务路径
    contextPath: 

spring:
    # 服务名称
    application:
        name: goods
    # 服务当前使用的profile
    profiles: 
        active: dev
    jackson:
        # json中日期是否用timestamps格式交互
        serialization.write-dates-as-timestamps: true
        # json中遇到无效变量是否报错
        deserialization.FAIL_ON_UNKNOWN_PROPERTIES: off
     # 数据库相关设置
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1/goods?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
        username: root
        password: rd123456
        test-while-idle: true
        max-wait-millis: 30000
        validation-query: 'SELECT 1'
        time-between-eviction-runs-millis: 20000
        min-evictable-idle-time-millis: 28700
    # JPA相关设置
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate.ddl-auto: update
        show-sql: true
    cache:
        ehcache:
          config: classpath:config/ehcache.xml

# LOG相关设置
logging:
    path: /var/log/goods
