server: 
    # 服务端口
    port: @server.port@
    # 服务路径
    contextPath: @server.contextpath@

spring:
    # 服务名称
    application:
        name: orders
    # 服务当前使用的profile
    profiles: 
        active: @spring.profiles.active@
    jackson:
        # json中日期是否用timestamps格式交互
        serialization.write-dates-as-timestamps: true
        # json中遇到无效变量是否报错
        deserialization.FAIL_ON_UNKNOWN_PROPERTIES: off
     # 数据库相关设置
    datasource:
        driver-class-name: @datasource.driver@
        url: @datasource.url@
        username: @datasource.username@
        password: @datasource.password@
        test-while-idle: true
        max-wait-millis: 30000
        validation-query: 'SELECT 1'
        time-between-eviction-runs-millis: 20000
        min-evictable-idle-time-millis: 28700
    # JPA相关设置
    jpa:
        database-platform: @datasource.dialect@
        hibernate.ddl-auto: @datasource.jpa.hibernate.ddl-auto@
        show-sql: @datasource.jpa.show-sql@

        # REDIS (RedisProperties)
    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: localhost
        # Redis服务器连接端口
        port: 32768
        # Redis服务器连接密码（默认为空）
#        password:
        pool:
            # 连接池最大连接数（使用负值表示没有限制）
            max-active: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1
            # 连接池中的最大空闲连接
            max-idle: 8
            # 连接池中的最小空闲连接
            min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0
    rocketmq:
        nameServer: localhost:9876
        producer-group-name: order-producer-group

# LOG相关设置
logging:
    path: @logging.path@
